[phases.setup]
nixPkgs = ['nodejs_22']
aptPkgs = ['curl', 'wget']

[phases.install]
cmds = ['corepack enable && pnpm install --frozen-lockfile']

[phases.build]
cmds = ['pnpm run build']

[start]
cmd = 'npx serve dist'

[variables]
NODE_ENV = 'production'
